Манифест, themes.xml, add_fragment выравнивание, BottomSheetDialog при нажатии на "Опубликовать"
mailru-android-edu/BLDJ pull request #12
Opened 2021-04-23 21:40 UTC by EdwardNee

2021-04-24 23:26 UTC, washinson requested changes
Реши вопрос с грэдлом и настрой фрагмент независимым от активити. Остальное по желанию

2021-04-24 23:26 UTC, washinson commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Где это используется? Надо убрать

2021-04-24 23:26 UTC, washinson commented on app/src/main/java/com/bldj/project/CreateFragment.kt
> +            bottomSheet.show((activity as FragmentActivity).supportFragmentManager, "TAG")
Фрагмент нужно стремиться делать максимально независимым от активити.
Для этого у ведра есть куча полезных шняг у `Fragment`. Одна из них - `requreFragmentManager()`. Что делает очев)

2021-04-24 23:26 UTC, washinson commented on app/src/main/java/com/bldj/project/MainActivity.kt
> +import java.security.InvalidParameterException
Не нужно?

2021-04-24 23:26 UTC, washinson commented on app/src/main/java/com/bldj/project/MainActivity.kt
> +        if (savedInstanceState == null)
жоско

2021-04-24 23:26 UTC, washinson commented on app/src/main/res/layout/fragment_bottom_sheet_create.xml
> +            android:layout_gravity="center|top"
ачовсмысле

2021-04-25 09:13 UTC, EdwardNee commented on app/src/main/res/layout/fragment_bottom_sheet_create.xml
> +            android:layout_gravity="center|top"
а шо тут?(

2021-04-25 18:10 UTC, washinson approved these changes
Верстку не чекал, надеюсь там все ок. Можно мержить

2021-04-25 18:10 UTC, washinson commented on app/src/main/res/layout/fragment_bottom_sheet_create.xml
> +            android:layout_gravity="center|top"
тебе в центр чи в топ?) 
есть такие штуки как `center_horizontal` и `center_vertical`. Они более идейно подходят сюда. Я так понимаю ты хотел бы использовать `center_horizontal|top`

2021-04-26 12:47 UTC, merged